// <auto-generated />
using System;
using AcademicPerformance.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicPerformance.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208174343_UniqueConstraints")]
    partial class UniqueConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AcademicPerformance.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScoreValue = 2,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ScoreValue = 4,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ScoreValue = 1,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            ScoreValue = 3,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            ScoreValue = 3,
                            StudentId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            ScoreValue = 5,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 7,
                            ScoreValue = 2,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            ScoreValue = 2,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 9,
                            ScoreValue = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 10,
                            ScoreValue = 5,
                            StudentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 11,
                            ScoreValue = 1,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 12,
                            ScoreValue = 1,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 13,
                            ScoreValue = 2,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 14,
                            ScoreValue = 3,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 15,
                            ScoreValue = 5,
                            StudentId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 16,
                            ScoreValue = 2,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 17,
                            ScoreValue = 3,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 18,
                            ScoreValue = 1,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 19,
                            ScoreValue = 4,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 20,
                            ScoreValue = 2,
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 21,
                            ScoreValue = 1,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 22,
                            ScoreValue = 3,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 23,
                            ScoreValue = 1,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 24,
                            ScoreValue = 3,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 25,
                            ScoreValue = 2,
                            StudentId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 26,
                            ScoreValue = 2,
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 27,
                            ScoreValue = 5,
                            StudentId = 6,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 28,
                            ScoreValue = 3,
                            StudentId = 6,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 29,
                            ScoreValue = 3,
                            StudentId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 30,
                            ScoreValue = 3,
                            StudentId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 31,
                            ScoreValue = 3,
                            StudentId = 7,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 32,
                            ScoreValue = 3,
                            StudentId = 7,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 33,
                            ScoreValue = 3,
                            StudentId = 7,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 34,
                            ScoreValue = 4,
                            StudentId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 35,
                            ScoreValue = 1,
                            StudentId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 36,
                            ScoreValue = 2,
                            StudentId = 8,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 37,
                            ScoreValue = 3,
                            StudentId = 8,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 38,
                            ScoreValue = 4,
                            StudentId = 8,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 39,
                            ScoreValue = 3,
                            StudentId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 40,
                            ScoreValue = 2,
                            StudentId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 41,
                            ScoreValue = 3,
                            StudentId = 9,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 42,
                            ScoreValue = 5,
                            StudentId = 9,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 43,
                            ScoreValue = 2,
                            StudentId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 44,
                            ScoreValue = 1,
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 45,
                            ScoreValue = 4,
                            StudentId = 9,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 46,
                            ScoreValue = 2,
                            StudentId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 47,
                            ScoreValue = 3,
                            StudentId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 48,
                            ScoreValue = 4,
                            StudentId = 10,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 49,
                            ScoreValue = 1,
                            StudentId = 10,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 50,
                            ScoreValue = 1,
                            StudentId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 51,
                            ScoreValue = 1,
                            StudentId = 11,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 52,
                            ScoreValue = 3,
                            StudentId = 11,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 53,
                            ScoreValue = 3,
                            StudentId = 11,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 54,
                            ScoreValue = 2,
                            StudentId = 11,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 55,
                            ScoreValue = 2,
                            StudentId = 11,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 56,
                            ScoreValue = 4,
                            StudentId = 12,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 57,
                            ScoreValue = 3,
                            StudentId = 12,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 58,
                            ScoreValue = 3,
                            StudentId = 12,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 59,
                            ScoreValue = 1,
                            StudentId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 60,
                            ScoreValue = 1,
                            StudentId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 61,
                            ScoreValue = 1,
                            StudentId = 13,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 62,
                            ScoreValue = 4,
                            StudentId = 13,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 63,
                            ScoreValue = 4,
                            StudentId = 13,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 64,
                            ScoreValue = 2,
                            StudentId = 13,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 65,
                            ScoreValue = 3,
                            StudentId = 13,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 66,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 67,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 68,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 69,
                            ScoreValue = 2,
                            StudentId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 70,
                            ScoreValue = 3,
                            StudentId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 71,
                            ScoreValue = 4,
                            StudentId = 15,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 72,
                            ScoreValue = 5,
                            StudentId = 15,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 73,
                            ScoreValue = 3,
                            StudentId = 15,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 74,
                            ScoreValue = 3,
                            StudentId = 15,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 75,
                            ScoreValue = 5,
                            StudentId = 15,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 76,
                            ScoreValue = 1,
                            StudentId = 16,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 77,
                            ScoreValue = 2,
                            StudentId = 16,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 78,
                            ScoreValue = 1,
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 79,
                            ScoreValue = 4,
                            StudentId = 16,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 80,
                            ScoreValue = 1,
                            StudentId = 16,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 81,
                            ScoreValue = 4,
                            StudentId = 17,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 82,
                            ScoreValue = 1,
                            StudentId = 17,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 83,
                            ScoreValue = 2,
                            StudentId = 17,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 84,
                            ScoreValue = 3,
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 85,
                            ScoreValue = 2,
                            StudentId = 17,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 86,
                            ScoreValue = 1,
                            StudentId = 18,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 87,
                            ScoreValue = 5,
                            StudentId = 18,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 88,
                            ScoreValue = 1,
                            StudentId = 18,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 89,
                            ScoreValue = 2,
                            StudentId = 18,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 90,
                            ScoreValue = 2,
                            StudentId = 18,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 91,
                            ScoreValue = 5,
                            StudentId = 19,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 92,
                            ScoreValue = 1,
                            StudentId = 19,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 93,
                            ScoreValue = 3,
                            StudentId = 19,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 94,
                            ScoreValue = 3,
                            StudentId = 19,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 95,
                            ScoreValue = 1,
                            StudentId = 19,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 96,
                            ScoreValue = 5,
                            StudentId = 20,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 97,
                            ScoreValue = 1,
                            StudentId = 20,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 98,
                            ScoreValue = 1,
                            StudentId = 20,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 99,
                            ScoreValue = 3,
                            StudentId = 20,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 100,
                            ScoreValue = 1,
                            StudentId = 20,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 101,
                            ScoreValue = 3,
                            StudentId = 21,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 102,
                            ScoreValue = 5,
                            StudentId = 21,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 103,
                            ScoreValue = 3,
                            StudentId = 21,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 104,
                            ScoreValue = 4,
                            StudentId = 21,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 105,
                            ScoreValue = 2,
                            StudentId = 21,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 106,
                            ScoreValue = 2,
                            StudentId = 22,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 107,
                            ScoreValue = 5,
                            StudentId = 22,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 108,
                            ScoreValue = 1,
                            StudentId = 22,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 109,
                            ScoreValue = 3,
                            StudentId = 22,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 110,
                            ScoreValue = 1,
                            StudentId = 22,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 111,
                            ScoreValue = 3,
                            StudentId = 23,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 112,
                            ScoreValue = 3,
                            StudentId = 23,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 113,
                            ScoreValue = 4,
                            StudentId = 23,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 114,
                            ScoreValue = 5,
                            StudentId = 23,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 115,
                            ScoreValue = 2,
                            StudentId = 23,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 116,
                            ScoreValue = 1,
                            StudentId = 24,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 117,
                            ScoreValue = 2,
                            StudentId = 24,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 118,
                            ScoreValue = 1,
                            StudentId = 24,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 119,
                            ScoreValue = 5,
                            StudentId = 24,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 120,
                            ScoreValue = 2,
                            StudentId = 24,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 121,
                            ScoreValue = 4,
                            StudentId = 25,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 122,
                            ScoreValue = 3,
                            StudentId = 25,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 123,
                            ScoreValue = 2,
                            StudentId = 25,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 124,
                            ScoreValue = 1,
                            StudentId = 25,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 125,
                            ScoreValue = 4,
                            StudentId = 25,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 126,
                            ScoreValue = 3,
                            StudentId = 26,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 127,
                            ScoreValue = 2,
                            StudentId = 26,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 128,
                            ScoreValue = 1,
                            StudentId = 26,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 129,
                            ScoreValue = 2,
                            StudentId = 26,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 130,
                            ScoreValue = 1,
                            StudentId = 26,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 131,
                            ScoreValue = 1,
                            StudentId = 27,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 132,
                            ScoreValue = 2,
                            StudentId = 27,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 133,
                            ScoreValue = 3,
                            StudentId = 27,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 134,
                            ScoreValue = 4,
                            StudentId = 27,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 135,
                            ScoreValue = 4,
                            StudentId = 27,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2006, 11, 1, 3, 26, 54, 869, DateTimeKind.Local).AddTicks(1948),
                            Name = "Winfield Upton"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 9, 17, 5, 11, 57, 651, DateTimeKind.Local).AddTicks(9559),
                            Name = "Randall Ritchie"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1998, 1, 19, 17, 7, 8, 948, DateTimeKind.Local).AddTicks(6233),
                            Name = "Agustina Cormier"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 11, 10, 18, 18, 5, 178, DateTimeKind.Local).AddTicks(8548),
                            Name = "Lolita Vandervort"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1996, 3, 12, 17, 34, 35, 38, DateTimeKind.Local).AddTicks(6932),
                            Name = "Claire Koepp"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1999, 1, 8, 15, 4, 45, 445, DateTimeKind.Local).AddTicks(4523),
                            Name = "Rose Mann"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1997, 6, 30, 19, 27, 34, 973, DateTimeKind.Local).AddTicks(4087),
                            Name = "Adalberto Weimann"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1994, 12, 21, 12, 51, 11, 712, DateTimeKind.Local).AddTicks(5837),
                            Name = "Alberto Satterfield"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2005, 11, 24, 15, 24, 18, 107, DateTimeKind.Local).AddTicks(6267),
                            Name = "Nico Nienow"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1997, 3, 8, 0, 12, 1, 74, DateTimeKind.Local).AddTicks(7629),
                            Name = "Stefan Lebsack"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2007, 1, 27, 1, 38, 49, 780, DateTimeKind.Local).AddTicks(8583),
                            Name = "Laurine Stehr"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1996, 6, 7, 12, 13, 23, 521, DateTimeKind.Local).AddTicks(4206),
                            Name = "Antonina McLaughlin"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2001, 6, 14, 2, 40, 59, 787, DateTimeKind.Local).AddTicks(2341),
                            Name = "Terrance DuBuque"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2009, 2, 24, 2, 46, 10, 578, DateTimeKind.Local).AddTicks(8750),
                            Name = "Phoebe Waters"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2007, 1, 19, 11, 47, 56, 953, DateTimeKind.Local).AddTicks(8966),
                            Name = "Jeramy Dickinson"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2001, 1, 30, 15, 0, 3, 910, DateTimeKind.Local).AddTicks(6559),
                            Name = "Bessie Denesik"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2006, 2, 20, 10, 54, 57, 233, DateTimeKind.Local).AddTicks(9166),
                            Name = "Carter Kris"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2003, 9, 5, 21, 33, 12, 275, DateTimeKind.Local).AddTicks(1892),
                            Name = "Carissa Anderson"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1996, 12, 27, 15, 8, 5, 103, DateTimeKind.Local).AddTicks(326),
                            Name = "Renee Willms"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1996, 7, 21, 0, 26, 26, 273, DateTimeKind.Local).AddTicks(3430),
                            Name = "Naomi Bednar"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(2004, 12, 27, 21, 57, 5, 890, DateTimeKind.Local).AddTicks(4034),
                            Name = "Franco Carroll"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1995, 11, 9, 6, 42, 35, 107, DateTimeKind.Local).AddTicks(7391),
                            Name = "Amos Barton"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(2008, 11, 4, 17, 6, 35, 368, DateTimeKind.Local).AddTicks(109),
                            Name = "Myles Carroll"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2000, 9, 18, 13, 55, 22, 513, DateTimeKind.Local).AddTicks(8454),
                            Name = "Winnifred Ward"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1995, 1, 30, 19, 42, 5, 597, DateTimeKind.Local).AddTicks(8847),
                            Name = "Rosendo Ebert"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2004, 4, 29, 16, 15, 21, 831, DateTimeKind.Local).AddTicks(7693),
                            Name = "Donna Lemke"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2002, 3, 11, 14, 11, 43, 818, DateTimeKind.Local).AddTicks(1747),
                            Name = "Dejah Nitzsche"
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Score", b =>
                {
                    b.HasOne("AcademicPerformance.Entities.Student", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicPerformance.Entities.Subject", "Subject")
                        .WithMany("Scores")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Student", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Subject", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
