// <auto-generated />
using System;
using AcademicPerformance.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicPerformance.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241206093301_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AcademicPerformance.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScoreValue = 3,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ScoreValue = 4,
                            StudentId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            ScoreValue = 2,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            ScoreValue = 3,
                            StudentId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 5,
                            ScoreValue = 3,
                            StudentId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            ScoreValue = 5,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 7,
                            ScoreValue = 2,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            ScoreValue = 2,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 9,
                            ScoreValue = 4,
                            StudentId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 10,
                            ScoreValue = 5,
                            StudentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 11,
                            ScoreValue = 2,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 12,
                            ScoreValue = 2,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 13,
                            ScoreValue = 3,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 14,
                            ScoreValue = 3,
                            StudentId = 3,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 15,
                            ScoreValue = 5,
                            StudentId = 3,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 16,
                            ScoreValue = 3,
                            StudentId = 4,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 17,
                            ScoreValue = 3,
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 18,
                            ScoreValue = 2,
                            StudentId = 4,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 19,
                            ScoreValue = 4,
                            StudentId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 20,
                            ScoreValue = 3,
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 21,
                            ScoreValue = 2,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 22,
                            ScoreValue = 4,
                            StudentId = 5,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 23,
                            ScoreValue = 2,
                            StudentId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 24,
                            ScoreValue = 4,
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 25,
                            ScoreValue = 3,
                            StudentId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 26,
                            ScoreValue = 3,
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 27,
                            ScoreValue = 5,
                            StudentId = 6,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 28,
                            ScoreValue = 4,
                            StudentId = 6,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 29,
                            ScoreValue = 4,
                            StudentId = 6,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 30,
                            ScoreValue = 3,
                            StudentId = 6,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 31,
                            ScoreValue = 4,
                            StudentId = 7,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 32,
                            ScoreValue = 3,
                            StudentId = 7,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 33,
                            ScoreValue = 3,
                            StudentId = 7,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 34,
                            ScoreValue = 4,
                            StudentId = 7,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 35,
                            ScoreValue = 2,
                            StudentId = 7,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 36,
                            ScoreValue = 3,
                            StudentId = 8,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 37,
                            ScoreValue = 4,
                            StudentId = 8,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 38,
                            ScoreValue = 4,
                            StudentId = 8,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 39,
                            ScoreValue = 4,
                            StudentId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 40,
                            ScoreValue = 2,
                            StudentId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 41,
                            ScoreValue = 4,
                            StudentId = 9,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 42,
                            ScoreValue = 5,
                            StudentId = 9,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 43,
                            ScoreValue = 2,
                            StudentId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 44,
                            ScoreValue = 2,
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 45,
                            ScoreValue = 5,
                            StudentId = 9,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 46,
                            ScoreValue = 2,
                            StudentId = 10,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 47,
                            ScoreValue = 4,
                            StudentId = 10,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 48,
                            ScoreValue = 5,
                            StudentId = 10,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 49,
                            ScoreValue = 2,
                            StudentId = 10,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 50,
                            ScoreValue = 2,
                            StudentId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 51,
                            ScoreValue = 2,
                            StudentId = 11,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 52,
                            ScoreValue = 3,
                            StudentId = 11,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 53,
                            ScoreValue = 4,
                            StudentId = 11,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 54,
                            ScoreValue = 3,
                            StudentId = 11,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 55,
                            ScoreValue = 3,
                            StudentId = 11,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 56,
                            ScoreValue = 5,
                            StudentId = 12,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 57,
                            ScoreValue = 4,
                            StudentId = 12,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 58,
                            ScoreValue = 3,
                            StudentId = 12,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 59,
                            ScoreValue = 2,
                            StudentId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 60,
                            ScoreValue = 2,
                            StudentId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 61,
                            ScoreValue = 2,
                            StudentId = 13,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 62,
                            ScoreValue = 4,
                            StudentId = 13,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 63,
                            ScoreValue = 4,
                            StudentId = 13,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 64,
                            ScoreValue = 2,
                            StudentId = 13,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 65,
                            ScoreValue = 3,
                            StudentId = 13,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 66,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 67,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 68,
                            ScoreValue = 4,
                            StudentId = 14,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 69,
                            ScoreValue = 3,
                            StudentId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 70,
                            ScoreValue = 3,
                            StudentId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 71,
                            ScoreValue = 4,
                            StudentId = 15,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 72,
                            ScoreValue = 5,
                            StudentId = 15,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 73,
                            ScoreValue = 4,
                            StudentId = 15,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 74,
                            ScoreValue = 3,
                            StudentId = 15,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 75,
                            ScoreValue = 5,
                            StudentId = 15,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 76,
                            ScoreValue = 2,
                            StudentId = 16,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 77,
                            ScoreValue = 3,
                            StudentId = 16,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 78,
                            ScoreValue = 2,
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 79,
                            ScoreValue = 5,
                            StudentId = 16,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 80,
                            ScoreValue = 2,
                            StudentId = 16,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 81,
                            ScoreValue = 5,
                            StudentId = 17,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 82,
                            ScoreValue = 2,
                            StudentId = 17,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 83,
                            ScoreValue = 3,
                            StudentId = 17,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 84,
                            ScoreValue = 4,
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 85,
                            ScoreValue = 3,
                            StudentId = 17,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 86,
                            ScoreValue = 2,
                            StudentId = 18,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 87,
                            ScoreValue = 5,
                            StudentId = 18,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 88,
                            ScoreValue = 2,
                            StudentId = 18,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 89,
                            ScoreValue = 3,
                            StudentId = 18,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 90,
                            ScoreValue = 3,
                            StudentId = 18,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 91,
                            ScoreValue = 5,
                            StudentId = 19,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 92,
                            ScoreValue = 2,
                            StudentId = 19,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 93,
                            ScoreValue = 4,
                            StudentId = 19,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 94,
                            ScoreValue = 3,
                            StudentId = 19,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 95,
                            ScoreValue = 2,
                            StudentId = 19,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 96,
                            ScoreValue = 5,
                            StudentId = 20,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 97,
                            ScoreValue = 2,
                            StudentId = 20,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 98,
                            ScoreValue = 2,
                            StudentId = 20,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 99,
                            ScoreValue = 4,
                            StudentId = 20,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 100,
                            ScoreValue = 2,
                            StudentId = 20,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 101,
                            ScoreValue = 3,
                            StudentId = 21,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 102,
                            ScoreValue = 5,
                            StudentId = 21,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 103,
                            ScoreValue = 3,
                            StudentId = 21,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 104,
                            ScoreValue = 5,
                            StudentId = 21,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 105,
                            ScoreValue = 3,
                            StudentId = 21,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 106,
                            ScoreValue = 3,
                            StudentId = 22,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 107,
                            ScoreValue = 5,
                            StudentId = 22,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 108,
                            ScoreValue = 2,
                            StudentId = 22,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 109,
                            ScoreValue = 3,
                            StudentId = 22,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 110,
                            ScoreValue = 2,
                            StudentId = 22,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 111,
                            ScoreValue = 4,
                            StudentId = 23,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 112,
                            ScoreValue = 3,
                            StudentId = 23,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 113,
                            ScoreValue = 4,
                            StudentId = 23,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 114,
                            ScoreValue = 5,
                            StudentId = 23,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 115,
                            ScoreValue = 3,
                            StudentId = 23,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 116,
                            ScoreValue = 2,
                            StudentId = 24,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 117,
                            ScoreValue = 3,
                            StudentId = 24,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 118,
                            ScoreValue = 2,
                            StudentId = 24,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 119,
                            ScoreValue = 5,
                            StudentId = 24,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 120,
                            ScoreValue = 3,
                            StudentId = 24,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 121,
                            ScoreValue = 4,
                            StudentId = 25,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 122,
                            ScoreValue = 4,
                            StudentId = 25,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 123,
                            ScoreValue = 3,
                            StudentId = 25,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 124,
                            ScoreValue = 2,
                            StudentId = 25,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 125,
                            ScoreValue = 4,
                            StudentId = 25,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 126,
                            ScoreValue = 4,
                            StudentId = 26,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 127,
                            ScoreValue = 3,
                            StudentId = 26,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 128,
                            ScoreValue = 2,
                            StudentId = 26,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 129,
                            ScoreValue = 3,
                            StudentId = 26,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 130,
                            ScoreValue = 2,
                            StudentId = 26,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 131,
                            ScoreValue = 2,
                            StudentId = 27,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 132,
                            ScoreValue = 2,
                            StudentId = 27,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 133,
                            ScoreValue = 4,
                            StudentId = 27,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 134,
                            ScoreValue = 4,
                            StudentId = 27,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 135,
                            ScoreValue = 4,
                            StudentId = 27,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2006, 10, 29, 19, 16, 13, 402, DateTimeKind.Local).AddTicks(4170),
                            Name = "Winfield Upton"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 9, 14, 21, 1, 16, 185, DateTimeKind.Local).AddTicks(877),
                            Name = "Randall Ritchie"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1998, 1, 17, 8, 56, 27, 481, DateTimeKind.Local).AddTicks(7510),
                            Name = "Agustina Cormier"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 11, 8, 10, 7, 23, 711, DateTimeKind.Local).AddTicks(9802),
                            Name = "Lolita Vandervort"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1996, 3, 10, 9, 23, 53, 571, DateTimeKind.Local).AddTicks(8052),
                            Name = "Claire Koepp"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1999, 1, 6, 6, 54, 3, 978, DateTimeKind.Local).AddTicks(5612),
                            Name = "Rose Mann"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1997, 6, 28, 11, 16, 53, 506, DateTimeKind.Local).AddTicks(5156),
                            Name = "Adalberto Weimann"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1994, 12, 19, 4, 40, 30, 245, DateTimeKind.Local).AddTicks(6886),
                            Name = "Alberto Satterfield"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2005, 11, 22, 7, 13, 36, 640, DateTimeKind.Local).AddTicks(7293),
                            Name = "Nico Nienow"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1997, 3, 5, 16, 1, 19, 607, DateTimeKind.Local).AddTicks(8507),
                            Name = "Stefan Lebsack"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2007, 1, 24, 17, 28, 8, 313, DateTimeKind.Local).AddTicks(9444),
                            Name = "Laurine Stehr"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1996, 6, 5, 4, 2, 42, 54, DateTimeKind.Local).AddTicks(5041),
                            Name = "Antonina McLaughlin"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2001, 6, 11, 18, 30, 18, 320, DateTimeKind.Local).AddTicks(3149),
                            Name = "Terrance DuBuque"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2009, 2, 21, 18, 35, 29, 111, DateTimeKind.Local).AddTicks(9540),
                            Name = "Phoebe Waters"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2007, 1, 17, 3, 37, 15, 486, DateTimeKind.Local).AddTicks(9737),
                            Name = "Jeramy Dickinson"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2001, 1, 28, 6, 49, 22, 443, DateTimeKind.Local).AddTicks(7319),
                            Name = "Bessie Denesik"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2006, 2, 18, 2, 44, 15, 766, DateTimeKind.Local).AddTicks(9907),
                            Name = "Carter Kris"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2003, 9, 3, 13, 22, 30, 808, DateTimeKind.Local).AddTicks(2616),
                            Name = "Carissa Anderson"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1996, 12, 25, 6, 57, 23, 636, DateTimeKind.Local).AddTicks(1031),
                            Name = "Renee Willms"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1996, 7, 18, 16, 15, 44, 806, DateTimeKind.Local).AddTicks(4112),
                            Name = "Naomi Bednar"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(2004, 12, 25, 13, 46, 24, 423, DateTimeKind.Local).AddTicks(4689),
                            Name = "Franco Carroll"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1995, 11, 6, 22, 31, 53, 640, DateTimeKind.Local).AddTicks(8028),
                            Name = "Amos Barton"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(2008, 11, 2, 8, 55, 53, 901, DateTimeKind.Local).AddTicks(729),
                            Name = "Myles Carroll"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2000, 9, 16, 5, 44, 41, 46, DateTimeKind.Local).AddTicks(9051),
                            Name = "Winnifred Ward"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1995, 1, 28, 11, 31, 24, 130, DateTimeKind.Local).AddTicks(9430),
                            Name = "Rosendo Ebert"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2004, 4, 27, 8, 4, 40, 364, DateTimeKind.Local).AddTicks(8254),
                            Name = "Donna Lemke"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2002, 3, 9, 6, 1, 2, 351, DateTimeKind.Local).AddTicks(2282),
                            Name = "Dejah Nitzsche"
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Score", b =>
                {
                    b.HasOne("AcademicPerformance.Entities.Student", "Student")
                        .WithMany("Scores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademicPerformance.Entities.Subject", "Subject")
                        .WithMany("Scores")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Student", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("AcademicPerformance.Entities.Subject", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
